### ISSUE TITLE
Wont run/install on development version of Racket

### ISSUE THREAD

**Issue by willghatch** [bldl/magnolisp#1]
I was trying to wrestle this into working for some time on my git build of racket before I finally tried it on the 6.1 release and discovered it worked.  Raco pkg will complain about file conflicts in doc/manual and other places.

**Comment by hasu** [comment]
Confirmed that there were two conflicts with the 6.2 release. Those are now fixed so that things are working with a full 6.2 installation (dependencies are not correctly declared yet). Have yet to try any development builds (would expect things to break a little when the switch to the new scope-sets-based macro system happens). Thanks for the report.

**Comment by hasu** [comment]
Seems to work with a recent snapshot (version 6.2.0.5) as well, so assuming it's now fairly compatible with Racket HEAD (until scope sets are merged in). Declared some of the more essential dependencies as well, to support Minimal Racket installations (`raco setup` still has some undeclared dependency complaints, but they don't seem warranted).
