### ISSUE TITLE
Magnolisp produces an error with an unsaved file

### ISSUE THREAD

**Issue by acarrico** [bldl/magnolisp#4]
@hasu, please see:

https://github.com/racket/racket/issues/4846

**Comment by hasu** [comment]
Thank you for letting me know about that scenario.

I suppose a fix can be to simply not call `make-definfo-submodule` in that case, since presumably there would be no way to specify such an unnamed module to the Magnolisp compiler API, and so the submodule with information for translation is useless.

I've pushed such a change.
